name: "${projectName}"
version: "${projectVersion}"
main: "${projectGroup}.${projectName.toLowerCase()}.${moduleName}.RechenzentrumPlugin"
description: "${projectDescription}"
author: "${projectAuthor}"
website: "${projectWebsite}"
api-version: "${paperApiVersion}"