[versions]
adventure = "4.18.0"
paper = "1.21.3-R0.1-SNAPSHOT"
shadow = "8.+"
paperweight-userdev = "1.+"
licenser = "0.6.1"

[libraries]
adventure-api = { module = "net.kyori:adventure-api", version.ref = "adventure" }
adventure-text = { module = "net.kyori:adventure-text-minimessage", version.ref = "adventure" }
paper = { module = "io.papermc.paper:paper-api", version.ref = "paper" }
shadow = { module = "com.gradleup.shadow:shadow-gradle-plugin", version.ref = "shadow" }

[bundles]
adventure = ["adventure-api", "adventure-text"]

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
paperweight-userdev = { id = "io.papermc.paperweight.userdev", version.ref = "paperweight-userdev" }
conventions-java = { id = "rechenzentrum.java-conventions" }
conventions-shadow = { id = "rechenzentrum.shadow-conventions" }
conventions-export = { id = "rechenzentrum.export-conventions" }